spring.application.name=lte

# Port in local development is 8087 but in production is 8080
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

udp.port=16680

springdoc.swagger-ui.path=/swagger-ui.html

# API URLs
api.meter.base-url=https://iot-platform-meters-backend-production.up.railway.app/m3verificaciones/api/v1
api.message.base-url=https://iot-platform-messages-backend-production.up.railway.app/m3verificaciones/api/v1
api.consumption.base-url=https://iot-platform-consumption-backend-production.up.railway.app/m3verificaciones/api/v1/consumption
