spring.application.name=lte

# Port in local development is 8087 but in production is 8080
server.port=8080

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

udp.port=16680

springdoc.swagger-ui.path=/swagger-ui.html

# API URLs
api.meter.base-url=http://localhost:8082/m3verificaciones/api/v1
api.message.base-url=http://localhost:8085/m3verificaciones/api/v1
api.consumption.base-url=http://localhost:8086/m3verificaciones/api/v1/consumption

